### ISSUE TITLE
Invalid repository structure

### ISSUE THREAD

**Issue by danmarsden** [SN-RECIT-formation-a-distance/moodle-filter_recitautolink#5]
As mentioned previously in https://tracker.moodle.org/browse/CONTRIB-8820 - the structure of your repositories is non-standard and will prevent many people that use git to manage their plugin deployments from using your plugins.

Can you please restructure your plugins so that the moodle code sits in the root of your repository? - that way organisations can use git submodules / subtrees etc to deploy your code into their sites.

note - this is not a blocker for approval in the plugins db but it will annoy a lot of Moodle admins.

**Comment by gustavobazzo** [comment]
Hello @danmarsden, thank you for your feedback. 

Since the structure of the repository is not an obstacle to approval, we prefer to keep our structure like this, as this is our structure for all our plugins so far. One of the reasons is that we use the Git repository for other purposes, not just for Moodle deployment. 

In order to circumvent the aforementioned issue, and also concerning Moodle admins, we always place the Moodle zip file, with the version number, ready to be installed in each new release, as you can check here [https://github.com/SN-RECIT-formation-a-distance/moodle-filter_recitautolink/releases/tag/v1.15.1](url)

**Comment by danmarsden** [comment]
Please note this will prevent many organistaions from being able to use your plugins and you will likely get other complaints. A lot of sites  rely on git submodules or git subtree to install plugins rather than zip files and they won't be able to use any of your plugins.

I'd still strongly encourage you to reconsider this for all of your moodle plugins.

**Comment by mudrd8mz** [comment]
One solution might be to make use of submodules. So that the content of the `src` folder would be directly in the root of this `moodle-filter_recitautolink` repository. And it would be then included as a submodule called `src` in another repository as per the maintainers' preference.
